### ISSUE TITLE
HTML Pages

### ISSUE THREAD

**Issue by ricardobentin** [DevTinder/Project2#4]
Need the following pages:

- [x] Homepage for app
- [x] Customer Sign Up Page
- [x] Developer Sign Up Page
- [x] Sign in page (will work for both Customer and Developer)
- [x] Profile page for Developer
- [x] Profile page for Customera
- [x] Create a Project Page for Customer
- [ ] Review Project Matches for Project (in Customer view to select a Developer for project)
- [ ] Review Project Matches for Project (in Developer view to start working on a project)

**Comment by ricardobentin** [comment]
Need the following pages:

- [ ] Homepage for app
- [ ] Customer Sign Up Page
- [ ] Developer Sign Up Page
- [ ] Sign in page (will work for both Customer and Developer)
- [ ] Profile page for Developer
- [ ] Profile page for Customer
- [ ] Create a Project Page for Customer
- [ ] Review Project Matches for Project (in Customer view to select a Developer for project)
- [ ] Profile page for Developer

**Comment by ricardobentin** [comment]
@paichunwang can we do a pull request with your HTML files so that we can start to deliver data to the page?

**Comment by paichunwang** [comment]
@ricardobentin hey! sorry im still working on some front end elements, have not got to all the pages just yet. I've pushed what i've finished into my branch, feel free to check it out first. Sorry about the delay.

**Comment by ricardobentin** [comment]
No sweat man! So you want to do a pull request so we can merge it with
master?
