### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by juan-camilo11** [DevTinder/Project2#6]
implement authentication using passport.js

**Comment by ricardobentin** [comment]
@juan-camilo11 seems like this was sorted out on Saturday. can I close this?

**Comment by juan-camilo11** [comment]
Ill close it once I implement the pull request for the authentication branch I made. Im still working on implementing the web tokens

**Comment by ricardobentin** [comment]
Ok cool. Still need to do db associations as well.

**Comment by juan-camilo11** [comment]
yo so work was a little more intense than anticipated. Still going to have auth w/ web tokens ready by tomorrow, but worst case I will definitely have it by thursday! Just a heads up

**Comment by ricardobentin** [comment]
No sweat. I’ll work on associating the tables and see if I can get some
output to the front end.
